Make "bundle console" work
Reference: https://github.com/jeremyevans/sequel_pg/issues/17

Fixes this error:

    $ bundle console
    There was an error while trying to load the gem 'sequel_pg'.
    Gem Load Error is: uninitialized constant Sequel::Postgres
    Backtrace for gem load error is:
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:91:in `require'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:86:in `each'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:86:in `block in require'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:75:in `each'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:75:in `require'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler.rb:107:in `require'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli/console.rb:14:in `run'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:365:in `console'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:20:in `dispatch'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:11:in `start'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:32:in `block in <top (required)>'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:24:in `<top (required)>'
    /Users/dentarg/.gem/ruby/2.3.3/bin/bundle:22:in `load'
    /Users/dentarg/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'
    Bundler Error Backtrace:
    NameError: uninitialized constant Sequel::Postgres
    /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:91:in `require'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:86:in `each'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:86:in `block in require'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:75:in `each'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/runtime.rb:75:in `require'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler.rb:107:in `require'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli/console.rb:14:in `run'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:365:in `console'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:20:in `dispatch'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/cli.rb:11:in `start'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:32:in `block in <top (required)>'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
      /Users/dentarg/.gem/ruby/2.3.3/gems/bundler-1.14.2/exe/bundle:24:in `<top (required)>'
      /Users/dentarg/.gem/ruby/2.3.3/bin/bundle:22:in `load'
      /Users/dentarg/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'