Explain why the code scanning warning is ignored
This string ends up in the "justification" attribute in the SARIF
output, and apparently it is not valid SARIF if it isn't a string (it
was null).

From https://github.com/Starkast/wikimum/actions/runs/3465429770/jobs/5788144432#step:6:26

> Error: Unable to upload "output.sarif.json" as it is not valid SARIF: